//
// Generated file, do not edit! Created by nedtool 5.6 from msg.msg.
//

#ifndef __INET_MSG_M_H
#define __INET_MSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Msg;
class StateUpdateMessage;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/contract/ipv4/Ipv4Address_m.h" // import inet.networklayer.contract.ipv4.Ipv4Address

// cplusplus {{
#include <vector>
typedef std::vector<std::pair<int,int>> IntVector;
typedef std::vector<std::vector<std::pair<int,int>>> IntVectorV;
typedef struct msg_{
	int id; //sender
    std::string msg; //message  
    std::vector<std::pair<int,int>> view; //current view or view     
    std::vector<std::pair<int,int>> installView; //current view or view     
    std::vector<std::vector<std::pair<int,int>>> SEQcv; //in case of PROPOSE
    int join_or_leave; //in case of RECONFIG (1 -> join, 0 -> leave)
    int type; //type of messagge (PROPOSE, REC-CONFIRM, RECONFIG, ecc.)
    int cer; //message certificate in case of COMMIT or ACK
    std::vector<std::pair<int,int>> Vcer; //view in which certificate is collected in case of COMMIT
    int msgId;
    int install_or_update; //in case of INSTALL (1 -> install, 0 -> update)
    std::string typeS;
    int sender;
};
// }}


namespace inet {

/**
 * Class generated from <tt>msg.msg:59</tt> by nedtool.
 * <pre>
 * class Msg extends FieldsChunk
 * {
 *     chunkLength = B(1);
 * 
 *     int id; //sender
 * 
 *     string msg; //message
 * 
 *     IntVector view; //current view or view 
 * 
 *     IntVector installView; //current view or view 
 * 
 *     IntVectorV SEQcv; //in case of PROPOSE
 * 
 *     int join_or_leave; //in case of RECONFIG (1 -> join, 0 -> leave)
 * 
 *     int type; //type of messagge (PROPOSE, REC-CONFIRM, RECONFIG, ecc.)
 * 
 *     int cer = -1; //message certificate in case of COMMIT or ACK
 * 
 *     IntVector Vcer; //view in which certificate is collected in case of COMMIT
 * 
 *     simtime_t sendTime; //send time
 * 
 *     simtime_t arrivalTime; //arrival time
 * 
 *     int msgId = -1;
 * 
 *     int install_or_update; //in case of INSTALL (1 -> install, 0 -> update)
 * 
 *     string typeS;
 * 
 *     int sender = -1;
 * 
 *     int destId;
 * 
 * }
 * </pre>
 */
class Msg : public ::inet::FieldsChunk
{
  protected:
    int id = 0;
    omnetpp::opp_string msg;
    IntVector view;
    IntVector installView;
    IntVectorV SEQcv;
    int join_or_leave = 0;
    int type = 0;
    int cer = -1;
    IntVector Vcer;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;
    int msgId = -1;
    int install_or_update = 0;
    omnetpp::opp_string typeS;
    int sender = -1;
    int destId = 0;

  private:
    void copy(const Msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Msg&);

  public:
    Msg();
    Msg(const Msg& other);
    virtual ~Msg();
    Msg& operator=(const Msg& other);
    virtual Msg *dup() const override {return new Msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
    virtual const IntVector& getView() const;
    virtual IntVector& getViewForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<Msg*>(this)->getView());}
    virtual void setView(const IntVector& view);
    virtual const IntVector& getInstallView() const;
    virtual IntVector& getInstallViewForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<Msg*>(this)->getInstallView());}
    virtual void setInstallView(const IntVector& installView);
    virtual const IntVectorV& getSEQcv() const;
    virtual IntVectorV& getSEQcvForUpdate() { handleChange();return const_cast<IntVectorV&>(const_cast<Msg*>(this)->getSEQcv());}
    virtual void setSEQcv(const IntVectorV& SEQcv);
    virtual int getJoin_or_leave() const;
    virtual void setJoin_or_leave(int join_or_leave);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getCer() const;
    virtual void setCer(int cer);
    virtual const IntVector& getVcer() const;
    virtual IntVector& getVcerForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<Msg*>(this)->getVcer());}
    virtual void setVcer(const IntVector& Vcer);
    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);
    virtual omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(omnetpp::simtime_t arrivalTime);
    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
    virtual int getInstall_or_update() const;
    virtual void setInstall_or_update(int install_or_update);
    virtual const char * getTypeS() const;
    virtual void setTypeS(const char * typeS);
    virtual int getSender() const;
    virtual void setSender(int sender);
    virtual int getDestId() const;
    virtual void setDestId(int destId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Msg& obj) {obj.parsimUnpack(b);}

// cplusplus {{
#include <vector>
typedef std::vector<Msg*> MsgVector;
// }}

/**
 * Class generated from <tt>msg.msg:107</tt> by nedtool.
 * <pre>
 * class StateUpdateMessage extends FieldsChunk
 * {
 *     chunkLength = B(2);
 * 
 *     int id; //sender
 * 
 *     string msg; //message
 * 
 *     IntVector view; //current view or view 
 * 
 *     IntVector RECV; //current view or view 
 * 
 *     IntVector installView; //current view or view 
 * 
 *     IntVectorV SEQcv; //in case of PROPOSE
 * 
 *     int type; //type of messagge (PROPOSE, REC-CONFIRM, RECONFIG, ecc.)
 * 
 *     bool ack;
 * 
 *     MsgVector ack_value;
 * 
 *     bool conflicting;
 * 
 *     MsgVector conflicting_value;
 * 
 *     bool stored;
 * 
 *     MsgVector stored_value;
 * 
 *     simtime_t sendTime; //send time
 * 
 *     simtime_t arrivalTime; //arrival time
 * 
 *     string typeS;
 * 
 *     int destId;
 * 
 * }
 * </pre>
 */
class StateUpdateMessage : public ::inet::FieldsChunk
{
  protected:
    int id = 0;
    omnetpp::opp_string msg;
    IntVector view;
    IntVector RECV;
    IntVector installView;
    IntVectorV SEQcv;
    int type = 0;
    bool ack = false;
    MsgVector ack_value;
    bool conflicting = false;
    MsgVector conflicting_value;
    bool stored = false;
    MsgVector stored_value;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;
    omnetpp::opp_string typeS;
    int destId = 0;

  private:
    void copy(const StateUpdateMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StateUpdateMessage&);

  public:
    StateUpdateMessage();
    StateUpdateMessage(const StateUpdateMessage& other);
    virtual ~StateUpdateMessage();
    StateUpdateMessage& operator=(const StateUpdateMessage& other);
    virtual StateUpdateMessage *dup() const override {return new StateUpdateMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
    virtual const IntVector& getView() const;
    virtual IntVector& getViewForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<StateUpdateMessage*>(this)->getView());}
    virtual void setView(const IntVector& view);
    virtual const IntVector& getRECV() const;
    virtual IntVector& getRECVForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<StateUpdateMessage*>(this)->getRECV());}
    virtual void setRECV(const IntVector& RECV);
    virtual const IntVector& getInstallView() const;
    virtual IntVector& getInstallViewForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<StateUpdateMessage*>(this)->getInstallView());}
    virtual void setInstallView(const IntVector& installView);
    virtual const IntVectorV& getSEQcv() const;
    virtual IntVectorV& getSEQcvForUpdate() { handleChange();return const_cast<IntVectorV&>(const_cast<StateUpdateMessage*>(this)->getSEQcv());}
    virtual void setSEQcv(const IntVectorV& SEQcv);
    virtual int getType() const;
    virtual void setType(int type);
    virtual bool getAck() const;
    virtual void setAck(bool ack);
    virtual const MsgVector& getAck_value() const;
    virtual MsgVector& getAck_valueForUpdate() { handleChange();return const_cast<MsgVector&>(const_cast<StateUpdateMessage*>(this)->getAck_value());}
    virtual void setAck_value(const MsgVector& ack_value);
    virtual bool getConflicting() const;
    virtual void setConflicting(bool conflicting);
    virtual const MsgVector& getConflicting_value() const;
    virtual MsgVector& getConflicting_valueForUpdate() { handleChange();return const_cast<MsgVector&>(const_cast<StateUpdateMessage*>(this)->getConflicting_value());}
    virtual void setConflicting_value(const MsgVector& conflicting_value);
    virtual bool getStored() const;
    virtual void setStored(bool stored);
    virtual const MsgVector& getStored_value() const;
    virtual MsgVector& getStored_valueForUpdate() { handleChange();return const_cast<MsgVector&>(const_cast<StateUpdateMessage*>(this)->getStored_value());}
    virtual void setStored_value(const MsgVector& stored_value);
    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);
    virtual omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(omnetpp::simtime_t arrivalTime);
    virtual const char * getTypeS() const;
    virtual void setTypeS(const char * typeS);
    virtual int getDestId() const;
    virtual void setDestId(int destId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StateUpdateMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StateUpdateMessage& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MSG_M_H

