//
// Generated file, do not edit! Created by nedtool 5.6 from msg.msg.
//

#ifndef __INET_MSG_M_H
#define __INET_MSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class Msg;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/contract/ipv4/Ipv4Address_m.h" // import inet.networklayer.contract.ipv4.Ipv4Address

// cplusplus {{
#include <vector>
typedef std::vector<int> IntVector;
// }}


namespace inet {

/**
 * Class generated from <tt>msg.msg:34</tt> by nedtool.
 * <pre>
 * class Msg extends FieldsChunk
 * {
 *     chunkLength = B(1);
 * 
 *     int id; //sender
 * 
 *     string msg; //message
 * 
 *     IntVector view; //current view or view 
 * 
 *     IntVector SEQcv; //in case of PROPOSE
 * 
 *     int join_or_leave; //in case of RECONFIG
 * 
 *     int type; //type of messagge (PROPOSE, REC-CONFIRM, RECONFIG, ecc.)
 * 
 *     int cer; //message certificate in case of COMMIT or ACK
 * 
 *     int Vcer; //view in which certificate is collected in case of COMMIT
 * 
 *     simtime_t sendTime; //send time
 * 
 *     simtime_t arrivalTime; //arrival time
 * 
 *     int msgId;
 * 
 * }
 * </pre>
 */
class Msg : public ::inet::FieldsChunk
{
  protected:
    int id = 0;
    omnetpp::opp_string msg;
    IntVector view;
    IntVector SEQcv;
    int join_or_leave = 0;
    int type = 0;
    int cer = 0;
    int Vcer = 0;
    omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;
    int msgId = 0;

  private:
    void copy(const Msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Msg&);

  public:
    Msg();
    Msg(const Msg& other);
    virtual ~Msg();
    Msg& operator=(const Msg& other);
    virtual Msg *dup() const override {return new Msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
    virtual const IntVector& getView() const;
    virtual IntVector& getViewForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<Msg*>(this)->getView());}
    virtual void setView(const IntVector& view);
    virtual const IntVector& getSEQcv() const;
    virtual IntVector& getSEQcvForUpdate() { handleChange();return const_cast<IntVector&>(const_cast<Msg*>(this)->getSEQcv());}
    virtual void setSEQcv(const IntVector& SEQcv);
    virtual int getJoin_or_leave() const;
    virtual void setJoin_or_leave(int join_or_leave);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getCer() const;
    virtual void setCer(int cer);
    virtual int getVcer() const;
    virtual void setVcer(int Vcer);
    virtual omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(omnetpp::simtime_t sendTime);
    virtual omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(omnetpp::simtime_t arrivalTime);
    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Msg& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MSG_M_H

